### ISSUE TITLE
App state is never change after being running

### ISSUE THREAD

**Issue by corentindrouet** [Nanocloud/nanocloud#121]
After going to desktop (for example), the state of desktop app in base is always equal to "running".

what will happen if multiple users run the same application at the same time?
And close it at different times?

**Comment by dynamiccast** [comment]
The field `state` in model `App` is not supposed to represent if the app if running or not. It is here to trigger the launch of the application in the VDI. See https://github.com/Nanocloud/nanocloud/blob/master/api/controllers/AppController.js#L92 for more details.

> what will happen if multiple users run the same application at the same time?

No problem. Plaza will execute the app in their respective VDI

> And close it at different times?

You can't "close" an app. Setting `App.state = "close"`  or whatever other value won't change anything.
