### ISSUE TITLE
Regular users should not be able to see DELETE button on the page of an application

### ISSUE THREAD

**Issue by corentindrouet** [Nanocloud/nanocloud#129]
Step to reproduce:
- Create a regular user.
- Create an app.
- Create a group and assign the user and the app created before, in this group.
- Log with the regular user, and go to apps/<id of your app>

**Comment by dynamiccast** [comment]
The page to get the information about an application is only accessible if you hack the url. Otherwise, it is only displayed to administrator.
As long as the API prevents non admin users from deleting an app it's ok.
Not a bug.
