### ISSUE TITLE
Display update channel (automatic display resolution refresh) seems to not work

### ISSUE THREAD

**Issue by domrod** [Nanocloud/nanocloud#164]
On release 2.0.0beta2 (may be also in 2.0.0beta1), in my case, resizing the browser window has no effect on the VDI window size.

As a workaround, to resize the VDI, I have to go back in the web portal and reconnect to the VDI.

My config:
- Docker containers in a dedicated server
- IaaS for Windows VM : AWS

Is it due to my hybrid config? Have you noticed the issue in other cases?

**Comment by dynamiccast** [comment]
This is a bug I can reproduce. Thanks for the ticket.
I will let you know what I found.

**Comment by dynamiccast** [comment]
Problem found: guacd is run from the official guacd image from glyptodon.
To fix the display update channel issue we previously had some patches to apply to it : https://github.com/Nanocloud/community/tree/master/modules/guacd

This needs to be done so the screen resolution updates work.
