### ISSUE TITLE
VM is not release after onboarding application

### ISSUE THREAD

**Issue by marc-cabocel** [Nanocloud/nanocloud#194]
=== Version ===
v2.0.0 rc1

=== Steps to reproduce ===
- As an admin, go to Applications > Onboard an application
- Try to publish calc.exe (Windows > System32), it should be available with a basic 2012 Windows
- Once the app is published, go to Machines

=== Expected Result ===
- The VM used to onboard the app should be released

=== Actual Result ===
- The VM is still in use

=== Analysis ===
- If the admin doesn't notice it, the VM will stay up all time

**Comment by dynamiccast** [comment]
Not application anymore.
