### ISSUE TITLE
File explorer for teams

### ISSUE THREAD

**Issue by dynamiccast** [Nanocloud/nanocloud#199]
There is currently only a read only file explorer for team files.
We should be able to browse directory, download and drag and drop files to upload.

**Comment by ccarbone** [comment]
Support of Drag'n drop of files was also expected. Is it into this ticket or in another ticket?

**Comment by dynamiccast** [comment]
Indeed, file drag n drop is in this ticket. Let me update the description.
The only thing that will not be covered is the file deletion from the web interface (still possible from Windows).

**Comment by ccarbone** [comment]
Just to be sure I was speaking about drag'n drop files to move them from one folder to another folder, both folders are in the cloud (not the drag n drop from your laptop to the cloud).

**Comment by dynamiccast** [comment]
@ccarbone the feature you describe is not part of this ticket.
It would require some change in the file API since plaza is currently not able to rename files.
This issue is only focusing on a frontend implementation for the team's file explorer to put it on the same level as what is already available for personal storage and application publication.
