### ISSUE TITLE
No need to set a default value for AWS_IMAGE

### ISSUE THREAD

**Issue by marc-cabocel** [Nanocloud/nanocloud#217]
=== Version ===
- v2.0.0

=== Steps to reproduce ===
- By default, the value of AWS_IMAGE is set to ami-09e61366. However, the ami ID depends on the AWS region. So this ami-ID will only be available for one region. In order to avoid setup issues, I would recommend to remove this default value.

**Comment by dynamiccast** [comment]
The variable should then be described as mandatory in the README.
