### ISSUE TITLE
Reduce boot time on AWS

### ISSUE THREAD

**Issue by dynamiccast** [Nanocloud/nanocloud#218]
Currently, it takes approximately 3 minutes to boot an new machine on AWS from scratch.
This boot time could be reduced. Here are some techniques:

http://stackoverflow.com/questions/36925803/speed-up-windows-ami-startup-times

**Comment by dynamiccast** [comment]
@Erfane and @NanoMarc I would love to have a feedback here on what you have accomplished so far trying to reduce the boot time.

**Comment by marc-cabocel** [comment]
@dynamiccast, I configured a specific AMI with auto-logon on and I installed a classic shell instead. I didn't manage to reduce the boot time only the time to access the VDI/app publish the first time a user connect to a VM.

**Comment by dynamiccast** [comment]
Feel free to reopen this ticket if you have more lead on how to improve booting time.
