### ISSUE TITLE
Shutdown Application Server before creating AMI

### ISSUE THREAD

**Issue by marc-cabocel** [Nanocloud/nanocloud#224]
=== Version ===
- v2.0.0

=== New Enhancement ===
- Currently when an image is saved by Nanocloud, it is done without turning off the application server. This may cause problem at boot time with the new AMI. Indeed, a message shows up telling something went wrong with the platform.
  ![error_message](https://cloud.githubusercontent.com/assets/18396467/18512262/9913c9da-7a88-11e6-9b85-222386046a5f.png)

**Comment by dynamiccast** [comment]
Currently, `noReboot` is explicitly passed when creating an image: https://github.com/Nanocloud/nanocloud/blob/master/api/drivers/aws/driver.js#L403
We should see what happens if this option is disabled.
