### ISSUE TITLE
Expiration time is not accurate

### ISSUE THREAD

**Issue by marc-cabocel** [Nanocloud/nanocloud#237]
=== Version ===
- 2.0.0

=== Steps to reproduce ===
- Setup a Nanocloud 2.0 on AWS
- Configure a session duration to 3600s
- Go to a VDI, then go back to Nanocloud

=== Expected Result ===
- The expiration time starts at 1 hour

=== Actual Result ===
- The expiration time starts at 1 hour 30s

=== Analysis ===
- This inaccuracy can deceive the user with the real status of the VM (if we set expiration time to 60s)

**Comment by marc-cabocel** [comment]
![screen shot 2016-09-19 at 10 57 48](https://cloud.githubusercontent.com/assets/18396467/18627083/47f94564-7e59-11e6-9569-6aebf587d773.png)

**Comment by dynamiccast** [comment]
Duplicate with https://github.com/Nanocloud/nanocloud/issues/234
