### ISSUE TITLE
Cannot manually link user to VM with manual mode

### ISSUE THREAD

**Issue by marc-cabocel** [Nanocloud/nanocloud#262]
=== Version ===
- v2.0.0

=== New Enhancement ===
- The idea here is to configure Nanocloud in manual mode and to be able to manually link VM to users. Currently the second step is not possible

**Comment by dynamiccast** [comment]
Hi,

Actually there is a pretty straightfoward hack to do it:
1. In the `MACHINES` environment variable, add an attribute `user` containing the id for each users in each machine object
2. Set a very important session duration to avoid machine to be reassigned

**Comment by marc-cabocel** [comment]
Ok I'll test and valide this fix then.

Thank you

**Comment by dynamiccast** [comment]
How are we on this issue ?

**Comment by marc-cabocel** [comment]
Still troubleshooting, I'm having issues with imported image on AWS

**Comment by dynamiccast** [comment]
How can I help you ?

**Comment by marc-cabocel** [comment]
@dynamiccast, It is working fine with a session duration that doesn't exceed 1 209 600 (2 weeks).
If the session duration is higher, when a user disconnects from the VDI, he is also deleted from the user column in machine table. Then it is not possible to re-access the VDI.

**Comment by marc-cabocel** [comment]
Ok it seems the VM is unlink with the user before the expiration date, so it is not working.

**Comment by marc-cabocel** [comment]
Any update on this?

**Comment by corentindrouet** [comment]
Manual driver didn't work on V 2.1.0.
This is because no image are assigned to the machines.
