### ISSUE TITLE
When running an app after changing its name, this app will be run 2 or more times.

### ISSUE THREAD

**Issue by corentindrouet** [Nanocloud/nanocloud#265]
Step to reproduce:
- Go to the vdi, install google chrome, onboard the app and close the vdi.
- Run chrome and close the vdi (chrome will be run once).
- Now change the name of the chrome app, and run it again.
  Their is many chrome running.

**Comment by dynamiccast** [comment]
Not sure this is related to the application renaming. Clicking on an app will lunch it whether it's already running in an unclosed session.
This is an expected behavior.
