### ISSUE TITLE
'Is team admin' Checkbox is not working

### ISSUE THREAD

**Issue by romain-ortega** [Nanocloud/nanocloud#266]
In a user's profile, when team admin is enabled, checkbox 'Is team admin' is not working.

**Comment by dynamiccast** [comment]
Is this bug still effective ?

**Comment by Leblantoine** [comment]
When a user as admin create a team he cannot be a regular user in any team even a team he doesn't created. A regular user or an admin who has not created a team can be a regular user or an admin team in any team.
For an admin creator of a team the checkbox `Is team admin` in his profile page still checked as long as it belongs to a team.
An other admin can uncheck this box in an admin user profile page. It's work but in teams page this admin user is always marked as a team admin even if the box is unchecked.
