### ISSUE TITLE
Saving an image randomly fails on AWS

### ISSUE THREAD

**Issue by dynamiccast** [Nanocloud/nanocloud#274]
As originally reported by @NanoMarc 

=== Version ===
- 2.0.0

=== Steps to reproduce ===
- Setup a Nanocloud 2.0.0 on AWS
- Publish some app
- Wait one hour
- Open a VDI and try to save an image

=== Expected Result ===
- A new image is saved and an AMI is created

=== Actual Result ===
- It seems an error occur but the AMI has been created

=== Analysis ===
- If you try a second time to save the image, it works (a message says "OK" and an AMI is created)
- The problem seems not related to the timeout on AWS for the AMI creation
- Several customers have seen this issue

**Comment by corentindrouet** [comment]
This problem is solved by the pr #309

**Comment by dynamiccast** [comment]
Fixed by #309

**Comment by corentindrouet** [comment]
Image didn't failed in front, but never respond. So users can wait the image to load for hours.
