### ISSUE TITLE
Revamp AWS Windows Server 2012 to Windows desktop-like

### ISSUE THREAD

**Issue by Erfane** [Nanocloud/nanocloud#304]
When a user connects to his virtual desktop, he should experience a better environment. This could be achieved by:
- removing useless elements on the Desktop (Amazon shortcut icons in the background, Server Manager and Powershell shortcuts in the Task Bar) 
- adding Google Chrome
- adding Classic Shell (www.classicshell.net)
- providing Windows auto login (#319 created for this)

**Comment by dynamiccast** [comment]
> removing useless elements on the Desktop

What should be removed exactly ?

**Comment by Erfane** [comment]
Issue updated following your question.

**Comment by dynamiccast** [comment]
> providing Windows auto login

I fail to see how this could help the user to feel in a Windows desktop environment. This should be part of another issue so we can discuss the real motivation behind this.

**Comment by Erfane** [comment]
Done in #319

**Comment by dynamiccast** [comment]
Have anyone used www.classicshell.net ?
It appears to me more like a tool to bring more feature to the explorer.
I think what Nanocloud is looking for is a way to make Windows Server look more like WIndows desktop which is what Microsoft Desktop Experience does : https://technet.microsoft.com/en-us/library/cc772567(v=ws.11).aspx

**Comment by dynamiccast** [comment]
This issue is targeting Amazon Virtual machine only. We would need to create an AMI and optionally make it public for anyone to use : http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-intro.html

AMIs are regionalized. For now I propose to only target eu-central-1.
