### ISSUE TITLE
Apply session duration modification without using the VDI

### ISSUE THREAD

**Issue by marc-cabocel** [Nanocloud/nanocloud#308]
=== Version ===
- v2.0.1

=== New Enhancement ===
- To perform maintenance on Nanocloud platform, it is mandatory that all users release their virtual machine. If session duration is set to 1h, we have to wait 1h before applying modification on the system which is not possible.
- As an administrator, it could be really useful to modify on-the-fly the session duration of all the virtual machine

**Comment by dynamiccast** [comment]
If your concern is to shut down all machines before proceeding to an upgrade.
This feature will allow you to do it : https://github.com/Nanocloud/nanocloud/issues/293
It will be implemented by the end of the sprint.

**Comment by marc-cabocel** [comment]
Yes that should do the trick. Thx
