### ISSUE TITLE
Add a custom name for AMI created by Administrator

### ISSUE THREAD

**Issue by marc-cabocel** [Nanocloud/nanocloud#328]
=== Version ===
- v2.0.1

=== New Enhancement ===
- When a new AMI is created by Nanocloud, it could be useful to set a custom name for the created AMI.

**Comment by marc-cabocel** [comment]
Does this custom name is also used in the AWS platform manager?

**Comment by Gentux** [comment]
This pop-up asking the user to enter a name will be open for all iaas drivers.

**Comment by corentindrouet** [comment]
Yes, it set the aws name with the one specified by the user.
