### ISSUE TITLE
Empty tooltip in 'users' page

### ISSUE THREAD

**Issue by romain-ortega** [Nanocloud/nanocloud#331]
When clicking on team settings an empty tooltip is shown and disappear after clicking on it :
![screen shot 2016-10-06 at 14 55 06](https://cloud.githubusercontent.com/assets/17955572/19153023/fda678cc-8bd4-11e6-9536-a2ab84da0f2e.png)

**Comment by dynamiccast** [comment]
Fixed in https://github.com/Nanocloud/nanocloud/pull/352
