### ISSUE TITLE
Numeric keypad does not work properly in VDI

### ISSUE THREAD

**Issue by Gentux** [Nanocloud/nanocloud#417]
On keyboard with a number keypad, when keyboard indicate that number pad is active, it isn't in VDI.
When this same keyboard indicate number deactivated, it is in the VDI

**Comment by ccarbone** [comment]
Is it still in the current product? BTW, it is an issue w/ Guac or an issue w/ our code?

**Comment by dynamiccast** [comment]
Seems to be fixed on Guacd 0.10
https://github.com/apache/incubator-guacamole-server/pull/14
