### ISSUE TITLE
Reorganise Applications list inside an image

### ISSUE THREAD

**Issue by marc-cabocel** [Nanocloud/nanocloud#419]
=== Version ===
- v2.1.0

=== New enhancement ===
- Currently it seems the applications are sorted randomly inside an image. It would be a good idea to sort Desktop app first in the list.

**Comment by Gentux** [comment]
Is there other rules to apply to this sort ?
We just make the Desktop as the first app for every image ?

Proposition: We put Desktop in position 1 and then sort alphabetically

**Comment by marc-cabocel** [comment]
that's good for me, the main idea was to separate a bit the desktop from the other app
