### ISSUE TITLE
Bad machine assignement, when creating an image.

### ISSUE THREAD

**Issue by corentindrouet** [Nanocloud/nanocloud#429]
Steps to reproduce:
- Launch your vdi, and create an image.
- Now disconnect and go to machine page.

Expected result: 
- One machine is assigned to you.

Actual result:
- Two machines are assigned to you. (one is booting).

**Comment by corentindrouet** [comment]
When creating an image, the machine's image is update to the new image created.
But when disconnect from vdi, getMachineForUser function is called by sessionEnded function, with the first image of the machine, so getMachineForUser doesn't find any machine with this image, and reassigne one to the user.

**Comment by Gentux** [comment]
I thought PR #430 solved this issue, can you confirm it is solved and should be closed ?

**Comment by corentindrouet** [comment]
Yes PR #430 solved the problem.
