### ISSUE TITLE
AWS: keypair duplicate should be handled silently

### ISSUE THREAD

**Issue by dynamiccast** [Nanocloud/nanocloud#47]
Currently, running the backend twice with the same `awsKeyName` will result in a : 

```
error: InvalidKeyPair.Duplicate: The keypair 'xxxxxx' already exists.
```

**Comment by domrod** [comment]
Is there any improvement or workaround on this issue?

As far as I know, you need to generate a new Key to get rid of the error. 

Even after deleting previous build Docker containers, images and nanocloud directory, a new build will be stuck by this message, which sounds weird. Am I missing something?

**Comment by dynamiccast** [comment]
Hi,

This bug is still open and will receive attention in the following days.
Currently, we can workaround this issue in dev mode by setting `awsPrivateKey` to `/opt/back/id_rsa` in `config/env/develoment.js`. Make sure you get and keep `id_rsa` untouched in your working directory after that.
Alternatively, you can remove all auto generated keypair in your AWS console.
